name       : haskell-semigroups
version    : 0.19.1
release    : 4
source     :
    - https://hackage.haskell.org/package/semigroups-0.19.1/semigroups-0.19.1.tar.gz : 79e761e64b862564a3470d5d356cb6b060b14452d675859aed3b2d1e14646648
license    : BSD-3-Clause
component  : programming.haskell
summary    : In mathematics, a semigroup is an algebraic structure consisting of a set together with an associative binary operation.
description: |
    In mathematics, a semigroup is an algebraic structure consisting of a set together with an associative binary operation. A semigroup generalizes a monoid in that there might not exist an identity element. It also (originally) generalized a group (a monoid with all inverses) to a type where every element did not have to have an inverse, thus the name semigroup.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

