name       : haskell-semigroups
version    : 0.18.2
release    : 2
source     :
    - http://hackage.haskell.org/package/semigroups-0.18.2/semigroups-0.18.2.tar.gz : 5dc9ff8622af25412fb071098063da288cd408a844e67c3371b78daa86d5d0e4
license    : BSD-3-Clause
component  : programming.haskell
summary    : In mathematics, a semigroup is an algebraic structure consisting of a
    set together with an associative binary operation.
description: |
    In mathematics, a semigroup is an algebraic structure consisting of a set together with an associative binary operation. A semigroup generalizes a monoid in that there might not exist an identity element. It also (originally) generalized a group (a monoid with all inverses) to a type where every element did not have to have an inverse, thus the name semigroup.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-hashable
    - haskell-tagged
    - haskell-unordered-containers
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

